import os
from lista import *

os.system("cls")
#os.system("clear")

print("--- Testando Lista ---")
lista = Lista()
print(f"Vazia? {lista.vazia()}")
lista.inserir_inicio(10)
lista.inserir_final(20)
lista.inserir_inicio(5)
lista.inserir_final(30)
print(f"{lista.tamanho} <= TAMANHO DA LISTA")
print("-----------------primeiro teste---------------")
lista.exibir()
lista.remover_inicio()
lista.remover_final()
print(f"{lista.tamanho} <= TAMANHO DA LISTA")
print("-----------------segundo teste---------------")
lista.exibir()
lista.remover_final()
print(f"{lista.tamanho} <= TAMANHO DA LISTA")
print(f"Vazia? {lista.vazia()}")
print("-----------------Terceiro teste---------------")
lista.remover_final()
lista.remover_final()
print(f"{lista.tamanho} <= TAMANHO DA LISTA")
print(f"Vazia? {lista.vazia()}")